version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./envs/dev/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_exemplo
      - POSTGRES_PASSWORD=password_exemplo
      - POSTGRES_DB=db_exemplo

volumes:
  postgres_data:
